# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c5e0cdebdec77a6db8324bc9517f9bdedf857fc339d2cc438769879156896cf7d88dccab5cefc9cd994b79e92b37d03083a5bdcf1722d5172c014bdf9db0586

test:
  secret_key_base: 7b9144c08f383d2db1bf3b11ccb739382c7b23dea4201dd680dcc12cb53f8bb5fc076dc744f12e85fd4eaee4c1d538f208ae8131c9d2c0345e92c37e130414e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
